### ISSUE TITLE
Newer horse types do not taxidermy with their skin.

### ISSUE THREAD

**Issue by cgfiend** [bdew-wurm/taxidermy#2]
I am a player on the Mythmoor server.  We have the latest version of the taxidermy mod (per the admin).  

When we taxidermy a newer horse type, the skin reverts to an old type horse skin (gray or white).

All of the Data2 values generated by the Taxidermy Calc spreadsheet for the newer horses turn out as the white skin when you use a GM to create a taxi (either through preserved body method or taxidermy kit).

There is an error in your Taxidermy Calc spreadsheet.  Under the Templates tab, the Skewbald Pinto should be 8, but it is 9.  Gold Buckskin is 9.

**Comment by bdew** [comment]
Check that your properties file on the server has the right color mappings from here https://github.com/bdew-wurm/taxidermy/blob/master/mods/taxidermy.properties

**Comment by cgfiend** [comment]
Bdew,

There's still an error on the templates page of your Taxidermy Calc.  
Skewbald pinto is set to 9, it should be 8, because gold buckskin is 9.

Thanks.

**Comment by bdew** [comment]
fixed
